#ifdef _WIN32
	#define IMAGES_PATH "images\\"
	#define SCENES_PATH "scenes\\"
#else
	#define IMAGES_PATH "images/"
	#define SCENES_PATH "scenes/"
#endif

#define BUFFER_SIZE 16384
#define NAME_SIZE 1024
#define COMMAND_NAME_SIZE 1024
#define ERROR_SIZE 2048
#define IMAGE_FILENAME_SIZE 1024
#define PATH_SIZE 1024
#define MAIN_SCENE "main"
#define IMAGES 1024
#define SOUNDS 1024
#define VAR_NAME_SIZE 1024
#define SOUND_NAME_SIZE 1024

#define _WIDTH_DEFAULT 640
#define _HEIGHT_DEFAULT 480
#define _VERBOSE_DEFAULT 1
#define _MESSAGE_IMAGE_DEFAULT 1
#define _MESSAGEBOX_X_DEFAULT 0
#define _MESSAGEBOX_Y_DEFAULT 0
#define _MESSAGE_COLOR_R 0
#define _MESSAGE_COLOR_G 255
#define _MESSAGE_COLOR_B 255
#define _MESSAGE_COLOR_A 255
#define _CHOICE_COLOR_R 255
#define _CHOICE_COLOR_G 0
#define _CHOICE_COLOR_B 0
#define _CHOICE_COLOR_A 0
#define _MESSAGE_BG_COLOR_R 0
#define _MESSAGE_BG_COLOR_G 0
#define _MESSAGE_BG_COLOR_B 0
#define _MESSAGE_BG_COLOR_A 0
#define _CHOICE_BG_COLOR_R 255
#define _CHOICE_BG_COLOR_G 255
#define _CHOICE_BG_COLOR_B 255
#define _CHOICE_BG_COLOR_A 127

#define MESSAGE_LINE_SIZE 2048
#define MESSAGE_LINES 256

#define DEFAULT_FONT_SIZE 36.0

#define FONT_FILE "VeraMono.ttf"

